### ISSUE TITLE
Use git repository for rooms

### ISSUE THREAD

**Issue by vikrambombhi** [Hacker-Chatroom/Hacker-Chatroom-Server#4]
Ok so I this killer idea for how we can handle rooms but I need everyone's input. Essentially what I'm thinking is we make GitHub repositories into rooms. This way authentication can be a user's GitHub login and then all the hackers working on the same thing will automatically be connected. Basically the idea is to embed slack into the terminal but we won't have slackbot.

**Comment by JackyChiu** [comment]
^ Sorry was just showing Vikram how to assign people

**Comment by JackyChiu** [comment]
Let's look into this after we finish our basic chat 😄 

Maybe we could expand it to Github organizations too so that if you have multiple repo's it's still good. 
Another thing to add on would be like a Github integration for the current repo your in, so you can see who's recently pushed and what commits they've submitted

**Comment by vikrambombhi** [comment]
alright ill keep this open so I dont forget. And yea we can try adding that too

**Comment by BenEmdon** [comment]
Im good with that 👍 adding it to 'POST V1'
